on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push Docker Image

    steps:
      # Checkout the repo
      - name: Checkout repo
        uses: actions/checkout@v2

      # Setup Docker Buildx (optional, for advanced builds)
     # - name: Set up Docker Buildx
     #   uses: docker/setup-buildx-action@v2

    # Log in to Docker Hub (optional, only if you want to push the image)
    #- name: Log in to Docker Hub
     # uses: docker/login-action@v2
     # with:
     #   username: ${{ secrets.DOCKER_USERNAME }}
     #   password: ${{ secrets.DOCKER_PASSWORD }}

      # Build the Docker Image
      - name: Build Docker image
        run: docker build -t docker-demo:v1 .

      - name: Docker login
        run: | 
              docker login -u="${{ secrets.DOCKER_USERNAME }}" -p="${{ secrets.DOCKER_PASSWORD }}"
              docker images
              docker tag docker-demo:v1 iprashanth07/docker-demo:1.0.0
              docker images
              docker push iprashanth07/docker-demo:1.0.0