name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  name: "Indra"

jobs:
  build:
    runs-on: ubuntu-latest

#Build, Tag and push!
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD}}

# GITHUB_SHA environment variable, which is automatically provided by GitHub Actions and contains the commit SHA.
# Assign an ID to this step to use it later in the workflow to reference outputs from this step
# $GITHUB_SHA is an environment varaible provided by GitHub
# prints the full commit SHA.
# the cut command extracts characters 1 to 7 from the full commit SHA.
# assign the result to a new variable called "commit_sha" and the echo it.
      - name: Extract commit SHA
        id: vars
        run: echo "COMMIT_SHA=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: Debug COMMIT_SHA
        run: echo "Commit SHA is $COMMIT_SHA"

      - name: Build and tag Docker image
        run: docker build -t iprashanth07/helloworld-java:$COMMIT_SHA .

      - name: Push Docker image
        run: docker push iprashanth07/helloworld-java:$COMMIT_SHA

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 157.245.126.155
          username: root
          key:  ${{ secrets.PRIVATE_KEY}}
          port: 22
          script: |
                   whoami
                   pwd
                   mkdir Github_to_Droplet
                   cd Github_to_Droplet
                   touch test.yml